// <auto-generated />
using EmployeeManageMent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManageMent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210718113504_BookTable")]
    partial class BookTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManageMent.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Picture");

                    b.Property<int>("SumProperty");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "asad@gmail.com",
                            Name = "Asad",
                            SumProperty = 0
                        },
                        new
                        {
                            Id = 2,
                            Department = 3,
                            Email = "galib@gmail.com",
                            Name = "Galib",
                            SumProperty = 0
                        },
                        new
                        {
                            Id = 3,
                            Department = 1,
                            Email = "kamrul@gmail.com",
                            Name = "Kamrul",
                            SumProperty = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
